# This file is a template, and might need editing before it works on your project.
# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle
image: registry.gitlab.com/fearnixxgaming/docker/gitlab-ci-image:latest

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  ORG_GRADLE_PROJECT_fngNexusUser: "$CI_NEXUS_USER"
  ORG_GRADLE_PROJECT_fngNexusPass: "$CI_NEXUS_PASS"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script: gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle


test:
  stage: test
  script: gradle check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

publish_snapshot:
  stage: deploy
  script: gradle publish tarDistribution
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
  only:
    - bleeding
  artifacts:
    paths:
      - "build/distributions/*"
    expire_in: 30 days

publish_release:
  stage: deploy
  script: gradle publish
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
  variables:
    ORG_GRADLE_PROJECT_release: "true"
  only:
    - release
  artifacts:
    paths:
      - "build/distributions/*"
